language: go

go:
    - 1.7.4

before_install:
    - go get -t -v ./...

install:
    - go install ./main/...

script:
    - go test -race -coverprofile=coverage.txt -covermode=atomic ./src/Pigeon/...
