language: go

go:
    - 1.7.4

before_install:
    - go get -t -v ./pigeon/...

install:
    - go install ./pigeon/...

script:
    - go test -race -coverprofile=coverage.txt -covermode=atomic ./pigeon/...
